import Stripe from "stripe";
const webhookKey = process.env.STRIPE_WEBHOOK_SECRET;
const resendKey = process.env.RESEND_KEY;

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
};

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);

export async function handler(event) {
    if (event.httpMethod !== "POST") {
        return { statusCode: 405, body: "Method Not Allowed" };
    }

    const sig = event.headers["stripe-signature"];
    const rawbody = event.body;

    let stripeEvent;
    try {
        stripeEvent = stripe.webhooks.constructEvent(rawbody, sig, process.env.STRIPE_WEBHOOK_SECRET)
    } catch(err) {
        return {statusCode: 400, body: `Webhook Error: ${err.message}`};
    }

    if (stripeEvent.type === "checkout.session.completed") {
        const session = stripeEvent.data.object;
        const { fullName, email, phone, preferredDate, backupDate, backupDate2, message } = session.metadata || {};

        const orderHTML = `
        <p><b>New Booking Received</b></p>

        <p>A new customer just completed checkout.</p>

        <p><b>Customer details:</b><br>
        Name: ${fullName ?? ""}<br>
        Email: ${email ?? ""}<br>
        Phone: ${phone ?? ""}</p>

        <p><b>Preferred dates:</b><br>
        Preferred date: ${preferredDate}<br>
        Backup date: ${backupDate}<br>
        Second backup: ${backupDate2}</p>

        ${message ? `<p><b>Customer notes:</b><br>${message}</p>` : ""}

        <hr>
        <p>This order was automatically generated by your website’s booking form.</p>
        <p>Check your Stripe dashboard for payment details.</p>
        `;

        const cxHTML = `
        <p>Hi ${fullName},</p>

        <p>Thank you for booking with Tech Care Connect! We've received your request and will follow up soon to confirm your appointment time.</p>

        <p><b>Your details:</b><br>
        Name: ${fullName}<br>
        Email: ${email}<br>
        Phone: ${phone}</p>

        <p><b>Preferred dates:</b><br>
        Preferred date: ${preferredDate}<br>
        Backup date: ${backupDate}<br>
        Second backup date: ${backupDate2}</p>

        ${message ? `<p><b>Notes:</b><br>${message}</p>` : ""}

        <p>If anything changes, you can reply to this email and we'll adjust your booking.</p>

        <p>- Tech Care Connect</p>
        `;

        console.log("event session.metadata:", JSON.stringify(session.metadata));
        
        // Email that goes to the customer
        await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${resendKey}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                from: "onboarding@resend.dev",
                to: email,
                subject: `Thanks - we received your booking!`,
                html: cxHTML
            })
        });
        
        // Email to confirm appointment
        await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
                Authorization: `Bearer ${resendKey}`,
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                from: "onboarding@resend.dev",
                to: "shelcod@gmail.com",
                subject: "NEW APPOINTMENT BOOKED",
                html: orderHTML
            })
        });

        return {statusCode: 200, body: "ok"};
    }
}