# baseURL: "https://techcareconnect.netlify.app/"
title: "Tech Care Connect"
summaryLength: 20
theme: "hugo-up-business"
languageCode: "en-us"

build:
  command: "hugo --gc --minify"
  buildStats:
    enable: true

  cachebusters:
    - source: "assets/notwatching/hugo_stats\\.json"
      target: "css"

    - source: "(postcss|tailwind)\\.config\\.js"
      target: 'css'

taxonomies:
  series: "series"
  tags: "tags"

params:
  colors:
    bg: "#F5E8D0"
    primary: "#2C3E50"
    secondary: "#3FBFBC"
    tertiary: "#BFE0C6"