main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Our team"
    url: "/about"
    weight: 2

  - name: "Articles"
    url: "/articles"
    weight: 3

buttons:
  - name: "Book a Session"
    url: "/services"
    weight: 4

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Our team"
    url: "/about"
    weight: 2

  - name: "Articles"
    url: "/articles"
    weight: 3

  - name: "Book a Session"
    url: "/services"
    weight: 4
