main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Our Team"
    url: "/about"
    weight: 2

  - name: "Articles"
    url: "/articles"
    weight: 3

  - name: "Contact Us"
    url: "/contact"
    weight: 4

buttons:
  - name: "Book a Session"
    url: "/services"
    weight: 5

footer:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Our Team"
    url: "/about"
    weight: 2

  - name: "Articles"
    url: "/articles"
    weight: 3

  - name: "Contact Us"
    url: "/contact"
    weight: 4

  - name: "Book a Session"
    url: "/services"
    weight: 5
